### ISSUE TITLE
Create Inform -> Unicare UNICEF demo workflow

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/unicare-demo#1]
## Background, context, and business value
Create Inform -> Unicare UNICEF demo workflow

## The specific request, in as few words as possible

Create a workflow that maps and syncs forms received from Inform (ONA) and loads them to UNICARE (Primero). See [workflow](https://app.openfn.org/projects/d9f62043-6dc4-4f7c-aa85-e78acc5d3f34/w/0beb31a8-ede6-4e2a-8f9c-e2cf4eb51c42) below. 

<img width="715" alt="image" src="https://github.com/OpenFn/unicare-demo/assets/80456839/8f2398de-209b-4815-9d4c-d1134879f5ca">

### Job 1: Clean and map inform data
Map the inform data received using this [mapping specification](https://docs.google.com/spreadsheets/d/1d0IXdaI3yrvOUHdr0a6hGmUX6dhLLyK6pr8STrgcsDA/edit#gid=1275153608). 
Adaptor: Common
Input: https://app.openfn.org/projects/d9f62043-6dc4-4f7c-aa85-e78acc5d3f34/dataclips/d940a44a-6047-4556-a7bd-ae1b413c7724/show

### Job 2: Register case in Primero
Create the case in Primero using mapped data from job 1
LP credential to use: UNICARE Primero Dev
Adaptor: Primero

### ~Job3: Send Administrator Email Alert~ [**SKIP FOR NOW - maybe we'll add later**]
Path condition: If "How_urgent_is_this_case" = "urgent_or_immediate_action_needs_to_be_t" in original Inform data, send an email alert to aleksa@openfn.org
LP credential to use: ??
Adaptor: Mailgun

## How to test 
Submit a form [here](https://web.inform.unicef.org/x/gnGnow6d) to trigger the workflow. Confirm the case is sent to Primero

## Toggl
`UNICARE Demo`

**Comment by daissatou2** [comment]
@aleksa-krolls

1. please add Hunter to the project on app if you can override the limit on # of users
2. I am assuming we won't actually send an email alert for this demo? If correct, please remove the job 3 details above. Otherwise please provide a demo Mailgun account and sample email alert for Hunter.
3. I already tested what is required in Primero and the mapping spec includes everything.

**Comment by aleksa-krolls** [comment]
Thanks @daissatou2 
1. Added Hunter to the project
2. Let's skip Mailgun step for now - not sure we have a demo account
3. Nice! @hunterachieng when you work on this next week, pls work with Aissatou on any questions. This should be a fairly simple workflow, but a good chance to learn about Primero and its Adaptor (used in all of our UNICEF proejcts) :)

**Comment by hunterachieng** [comment]
@daissatou2 The workflow is ready for testing. Please have a look

**Comment by hunterachieng** [comment]
@josephjclark  Do you mind reviewing the above workflow?

**Comment by josephjclark** [comment]
@hunterachieng I'd love to take a look on Monday. Where is it? I can't see anything in the repo here. I might need privileges

**Comment by hunterachieng** [comment]
@daissatou2 Is it possible for you to add @josephjclark  to the project on lightening?

**Comment by daissatou2** [comment]
I've asked Taylor to do this [here](https://openfn.slack.com/archives/C03EQQB5W7R/p1717158380294409?thread_ts=1716566676.214549&cid=C03EQQB5W7R).

**Comment by aleksa-krolls** [comment]
I've added @josephjclark to the repo

**Comment by josephjclark** [comment]
I don't know how to leave feedback on Lightning directly, I guess I'll just leave some comments here!

The `Register Case in Primero` and `Send Administrator Email Alert` steps don't seem to be implemented? 

# Clean and map inform data

## Untidy comments

This comment should be removed from the top: `// Get started by adding operations from the API reference`.

 It  just looks untidy and makes me wonder if the job was autogenerated or blind-pasted in or something

## Difficult variable names

* @hunterachieng I know you asked me about this on slack but I think I'm going to change my mind. I'll explain why.

This deconstruction is pretty awkward:

```
 const { Your_first_name, Your_age_range, Your_last_name, Details_about_your_f_edback_or_complaints, How_urgent_is_this_case } = state.data;
```

First off it has to be formatted nicely and split over several lines so that someone can read it
```
 const {
    Your_first_name,
    Your_age_range,
    Your_last_name,... etc } = state.data;
```

Secondly, those variable names are a nightmare and kind of asking for trouble. I've seen this pattern in job code before and it just makes me anxious.

I would want to alias the field names into easier variables, and I would want to do so in a really declarative way that's easier for someone else to understand.

So maybe instead of deconstructing, I'd do this:

```
const { data } = state;
const firstName = data.Your_first_name
const lastName =  data.Your_last_name
```

I suppose the other option is to alias them directly into the upload format - although that still has some akward names

```
const { data } = state;
const name_first = data.Your_first_name
const name_last =  data.Your_last_name
```

## Pointless functions

I would avoid creating extra functions that are only called once, unless they're doing something really really complicated.

In this case, I think `ageRangeValue` and `caseRiskLevel` add more complexity than they removed?

## Suggested rewrite

This is untested but this is probably what I would do:

```
fn(state => {
  const { data } = state;

  const name_first =  data.Your_first_name;
  const lastName =  data.Your_last_name;
  const feedback_comment_f076498 = data.Details_about_your_f_edback_or_complaints

  let age = Number(data.Your_age_range);
  if (age > 0 && age <= 17) {
    age = '0_17_years_old_a619c9b';
  } else if (age >= 18 && age <= 59) {
    age = '18_59_years_old_b6fd344';
  } else {
    age = '60_and_above_b0f9d41';
  }

  const risk_level = data.How_urgent_is_this_case === 'urgent_or_immediate_action_needs_to_be_t' ? 'high' : 'low';

  state.informData = {
    name_first,
    name_last,
    feedback_comment_f076498,
    age_range_3df3bdb: age,
    risk_level
  }
  return state;
});

```

**Comment by josephjclark** [comment]
I've also noted this usage of condition labels  on edges:
![image](https://github.com/OpenFn/unicare-demo/assets/7052509/054772f8-e91f-41d6-88a7-3ce5cc6a0b9a)

This is fine but also not how the system was designed! Have you raised this with product team? The ability to add an edge label without a condition?

**Comment by hunterachieng** [comment]
@josephjclark I have fixed all issues.
For the edge cases, there is a condition in the one described. Do you mind explaining more in-case I might be off?

**Comment by josephjclark** [comment]
@hunterachieng the edges thing isn't for you to fix here, it's fine :)

It's a bit of wider feedback for @aleksa-krolls and guess @christad92.

I suppose you could replace `{}` with `true` in the condition, I'd be a bit happier about that, but it's really not important

**Comment by josephjclark** [comment]
@hunterachieng there's an error on the edge condition for `High risk case?` - the condition should be `===`, not `=`.

I still don't see any code in the email step - is that deliberate?

**Comment by hunterachieng** [comment]
@josephjclark  I was not to implement anything in the email step.
I am fixing the strictly equal to condition
